### ISSUE TITLE
net.sf.saxon.trans.XPathException error 

### ISSUE THREAD

**Issue by adam-trujillo** [jason-fox/fox.jason.translate.xliff#1]
Hello - when I try to execute the xliff-create transformation, the console prints this error message:
Error: net.sf.saxon.trans.XPathException: I/O error reported by XML parser processing file:/Users/atrujillo/Core/prototype/en/main-product-maps/topics/common-topics/parasoft-settings/dtp-settings/dtp.autoconfig.dita: /Users/atrujillo/Core/prototype/en/main-product-maps/topics/common-topics/parasoft-settings/dtp-settings/topic.dtd (No such file or directory)

I've successfully validated all of the dita and ditamap files in my project and do not understand what might be throwing the error. I am able to execute the other transformations (e.g., html5) with problem.

I am using DITA-OT 3.5.1 and have installed the org.doctales.xmltask plugin per the instructions.

Please let me know if any other information is necessary to help determine if this is a bug.

Thanks,
Adam

**Comment by jason-fox** [comment]
Could you attach the file `dtp.autoconfig.dita` to the issue? My guess is that the problem appears to be with the processing of the `DOCTYPE` statement.  I use the following:

```xml
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
```

Even better would be a simple 2 file `*.ditamap` including with the offending `dtp.autoconfig.dita` file.

Are you using `master` or a fixed release - e.g [v3.0.0](https://github.com/jason-fox/fox.jason.translate.xliff/releases/tag/v3.0.0)? If the former it could be a bug introduced in recent development.

**Comment by adam-trujillo** [comment]
[prototype.zip](https://github.com/jason-fox/fox.jason.translate.xliff/files/4983024/prototype.zip)
Thanks for looking into this. I've attached a skeleton of the project that I'm working with that should only render the contents of the dtp.autoconfig.dita file. 

I looked at the plugin.xml file and it says that it's version 3.0.0. 

Please let me know if there is anything else I can do to help.

**Comment by jason-fox** [comment]
### Diagnosis

The issue is definitely within the `DOCTYPE` processing.

I use (and am only able to process) `<topic>` files  using the following `topic.dtd` definition:

```xml
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
```
You can see the current list of acceptable types [here](https://github.com/jason-fox/fox.jason.translate.xliff/blob/master/build_dita2translate.xml#L34-#L39) in  `build_dita2translate.xml` and [here](https://github.com/jason-fox/fox.jason.translate.xliff/blob/master/build_dita2translate_template.xml#L34-#L39) in `tbuild_dita2translate_template.xml`. My DTD is the **non-versioned** generic one based on the [DITA 1.2 OASIS spec](https://docs.oasis-open.org/dita/v1.2/cd03/spec/archSpec/dtdorganization.html)

In your supplied file you are using 

```xml
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA 1.1 Topic//EN" "topic.dtd">
```

Which appears to be the **versioned** one from the older [DITA 1.1 OASIS spec](https://docs.oasis-open.org/dita/v1.1/CD01/archspec/dtdorganization.html).

Either way, that older 1.1  `DOCTYPE` isn't on my list for processing.

### Workaround


You have two options - either add the `-//OASIS//DTD DITA 1.1 Topic` to the list within `build_dita2translate.xml` and `build_dita2translate_template.xml`

```diff
<xmlcatalog id="fake.dita.catalog">
	<dtd publicId="-//OASIS//DTD DITA Topic//EN" location="${translate.resource.dir}/fake.dtd"/>
+	<dtd publicId="-//OASIS//DTD DITA 1.1 Topic//EN" location="${translate.resource.dir}/fake.dtd"/>
	<dtd publicId="-//OASIS//DTD DITA Map//EN" location="${translate.resource.dir}/fake.dtd"/>
	<dtd publicId="-//OASIS//DTD DITA BookMap//EN" location="${translate.resource.dir}/fake.dtd"/>
	<dtd publicId="-//OASIS//DTD DITA DITAVAL//EN" location="${translate.resource.dir}/fake.dtd"/>
	<dtd publicId="-//OASIS//DTD DITA Concept//EN" location="${translate.resource.dir}/fake.dtd"/>
	<dtd publicId="-//OASIS//DTD DITA Task//EN" location="${translate.resource.dir}/fake.dtd"/>
</xmlcatalog>
```

Or update the `DOCTYPE` declarations in your  `*.dita` to use the non-versioned declaration.

```diff
<?xml version='1.0' encoding='UTF-8'?>
- <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA 1.1 Topic//EN" "topic.dtd">
+ <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" ditaarch:DITAArchVersion="1.1" id="dtp-autoconfig-topic">
	<title>dtp.autoconfig</title>
```

**Comment by adam-trujillo** [comment]
Thank you! I was able successfully use the plugin by adding the versioned DOCTYPES to the files you specified. This plug-in will be a big help for us moving forward. Cheers!

**Comment by jason-fox** [comment]
I think

```diff
<xmlcatalog id="fake.dita.catalog">
-	<dtd publicId="-//OASIS//DTD DITA Topic//EN" location="${translate.resource.dir}/fake.dtd"/>
-	<dtd publicId="-//OASIS//DTD DITA Map//EN" location="${translate.resource.dir}/fake.dtd"/>
-	<dtd publicId="-//OASIS//DTD DITA BookMap//EN" location="${translate.resource.dir}/fake.dtd"/>
-	<dtd publicId="-//OASIS//DTD DITA DITAVAL//EN" location="${translate.resource.dir}/fake.dtd"/>
-	<dtd publicId="-//OASIS//DTD DITA Concept//EN" location="${translate.resource.dir}/fake.dtd"/>
-	<dtd publicId="-//OASIS//DTD DITA Task//EN" location="${translate.resource.dir}/fake.dtd"/>
+	<catalogpath path="${dita.plugin.org.dita.base.dir}/catalog-dita.xml"/>
</xmlcatalog>
```

Is probably a better fix in the long run. - this will need testing under windows to be certain.

**Comment by electronix** [comment]
Did you manage to test this change under Windows? I still get the same problem (using `<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">`).

Reverting the fake.dita.catalog to the values posted above solves the issue for me.

**Comment by jason-fox** [comment]
I've re-added the old fake DTDs and made another release. Try installing the new binary and see if that works for you:

```
dita install https://github.com/jason-fox/fox.jason.translate.xliff/archive/v3.1.1.zip
```

**Comment by electronix** [comment]
Works perfect for me. Thanks for the quick fix!
