### ISSUE TITLE
Question: will there be a new release soon?

### ISSUE THREAD

**Issue by pflotscher** [jason-fox/fox.jason.translate.xliff#6]
The current release (3.5.0) does not work with the current release of `org.doctales.xmltask` (1.16.1).  
Explicitly the command `dita -f xliff-dita %restofarguments%` throws an error the following one:  
```
jar:file:/opt/dita/plugins/fox.jason.translate.xliff/lib/translate-1.2.jar!/fox/jason/translate/antlib.xml:574: java.lang.IllegalAccessError: class com.oopsconsultancy.xmltask.jdk15.XPathAnalyser15 (in unnamed module @0x45283ce2) cannot access class com.sun.org.apache.xpath.internal.XPathAPI (in module java.xml) because module java.xml does not export com.sun.org.apache.xpath.internal to unnamed module @0x45283ce2
```  
Edit: I use openjdk-17 since DITA-OT requires version 17 or newer

These are the configurations I tested:  
**fox.jason.translate.xliff 3.5.0 & org.doctales.xmltask 1.16.1** -> is the current configuration in the DITA-OT registry, does not work due to the stated error
**fox.jason.translate.xliff 3.5.0 & org.jung.xmltask master HEAD** -> does not work because the name changed from org.doctales.xmltask to org.jung.xmltask, can be fixed easily  
**fox.jason.translate.xliff master HEAD (with dependency correction in plugin.xml) & org.jung.xmltask master HEAD** -> WORKS!  

Since org.jung.xmltask is changed frequently at the moment it would be nice to coordinate a release for both of them.  
Feel free to reach out to me if my description isn't precise enough :)

**Comment by jason-fox** [comment]
I have updated the plugin to remove the dependency and include its own version of the xmltask 88f73a0 - could you reinstall `master` and tell me if that works for you. If it does I can label a new release.

**Comment by pflotscher** [comment]
Every command works just fine. Thank you for the quick reaction!
