### ISSUE TITLE
translate.xlf does not contain contents since DITA-OT 4.1

### ISSUE THREAD

**Issue by pflotscher** [jason-fox/fox.jason.translate.xliff#7]
It looks like the plugin isn't working anymore since DITA-OT 4.1. With DITA-OT 4.0.2 the result looks as expected.  
The skl files are created correctly but the translate.xlf file contains nothing more than 
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0"
        xmlns:fs="urn:oasis:names:tc:xliff:fs:2.0"
        srcLang="en"
        trgLang="de"
        version="2.0"/>
```  
For now thats all I found out. I'll update on this when I know more about it.

**Comment by jason-fox** [comment]
This is due to changing merge functionality . Could you see if the XSLT update  5a4c6af fixes it.

```console
dita uninstall fox.jason.translate.xliff
dita install https://github.com/jason-fox/fox.jason.translate.xliff/archive/master.zip
```

It looks like the `id` attributes in XLIFF 1.2  have changed with the fix, but if this works I'll just amend the test expectations.

**Comment by pflotscher** [comment]
It works again. I was able to create a valid translate.xlf and a valid translated document.  
Thank you so much!!  
May I also ask you to extend [ReinsertDoctypeTask.java](https://github.com/jason-fox/fox.jason.translate.xliff/blob/master/src/fox/jason/translate/tasks/ReinsertDoctypeTask.java) with the doctypes `glossgroup` and `troubleshooting` ?
```
"PUBLIC \"-//OASIS//DTD DITA Glossary Group//EN\" \"glossgroup.dtd\""
"PUBLIC \"-//OASIS//DTD DITA Troubleshooting//EN\" \"troubleshooting.dtd\""
```
Currently it throws a `Unknown Doctype` message

**Comment by jason-fox** [comment]
Added [the doctypes](https://github.com/jason-fox/fox.jason.translate.xliff/commit/dabc739a084e0b13f377c559f6cf5516eeb0a215#diff-bc046c4fe6d1dc63eea7067f76c55b5baabffbfaf8b0916a126fc36460632360) - please pull latest.

**Comment by pflotscher** [comment]
Also works, thank you :)
